language: python
sudo: false
matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9
  - python: nightly
  - python: pypy3
  allow_failures:
  - python: nightly
before_install:
- curl -sL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python - -y
- export PATH=$PATH:$HOME/.local/bin
install:
- poetry install
script:
- poetry run pytest
after_success:
- codecov
